services:
  postgres:
    image: postgres:13.2
    container_name: products_app
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - products_app/products_app/.env
volumes:
  db_value:
